export const VAT_DELETE_RESET = 'VAT_DELETE_RESET'
export const VAT_DELETE_SET_ERROR = 'VAT_DELETE_SET_ERROR'
export const VAT_DELETE_SET_DELETED = 'VAT_DELETE_SET_DELETED'
export const VAT_DELETE_TOGGLE_LOADING = 'VAT_DELETE_TOGGLE_LOADING'
