export const CHANNEL_SHOW_RESET = 'CHANNEL_SHOW_RESET'
export const CHANNEL_SHOW_SET_ERROR = 'CHANNEL_SHOW_SET_ERROR'
export const CHANNEL_SHOW_SET_RETRIEVED = 'CHANNEL_SHOW_SET_RETRIEVED'
export const CHANNEL_SHOW_TOGGLE_LOADING = 'CHANNEL_SHOW_TOGGLE_LOADING'
