export const DOCUMENT_DELETE_RESET = 'DOCUMENT_DELETE_RESET'
export const DOCUMENT_DELETE_SET_ERROR = 'DOCUMENT_DELETE_SET_ERROR'
export const DOCUMENT_DELETE_SET_DELETED = 'DOCUMENT_DELETE_SET_DELETED'
export const DOCUMENT_DELETE_TOGGLE_LOADING = 'DOCUMENT_DELETE_TOGGLE_LOADING'
