export const TASKSTATUS_SHOW_RESET = 'TASKSTATUS_SHOW_RESET'
export const TASKSTATUS_SHOW_SET_ERROR = 'TASKSTATUS_SHOW_SET_ERROR'
export const TASKSTATUS_SHOW_SET_RETRIEVED = 'TASKSTATUS_SHOW_SET_RETRIEVED'
export const TASKSTATUS_SHOW_TOGGLE_LOADING = 'TASKSTATUS_SHOW_TOGGLE_LOADING'
