export const ORDERHEADER_DELETE_RESET = 'ORDERHEADER_DELETE_RESET'
export const ORDERHEADER_DELETE_SET_ERROR = 'ORDERHEADER_DELETE_SET_ERROR'
export const ORDERHEADER_DELETE_SET_DELETED = 'ORDERHEADER_DELETE_SET_DELETED'
export const ORDERHEADER_DELETE_TOGGLE_LOADING = 'ORDERHEADER_DELETE_TOGGLE_LOADING'
