export const TEMPLATETYPE_DELETE_RESET = 'TEMPLATETYPE_DELETE_RESET'
export const TEMPLATETYPE_DELETE_SET_ERROR = 'TEMPLATETYPE_DELETE_SET_ERROR'
export const TEMPLATETYPE_DELETE_SET_DELETED = 'TEMPLATETYPE_DELETE_SET_DELETED'
export const TEMPLATETYPE_DELETE_TOGGLE_LOADING = 'TEMPLATETYPE_DELETE_TOGGLE_LOADING'
