export const PROJECT_SHOW_RESET = 'PROJECT_SHOW_RESET'
export const PROJECT_SHOW_SET_ERROR = 'PROJECT_SHOW_SET_ERROR'
export const PROJECT_SHOW_SET_RETRIEVED = 'PROJECT_SHOW_SET_RETRIEVED'
export const PROJECT_SHOW_TOGGLE_LOADING = 'PROJECT_SHOW_TOGGLE_LOADING'
