export const INVOICEHEADER_SHOW_RESET = 'INVOICEHEADER_SHOW_RESET'
export const INVOICEHEADER_SHOW_SET_ERROR = 'INVOICEHEADER_SHOW_SET_ERROR'
export const INVOICEHEADER_SHOW_SET_RETRIEVED = 'INVOICEHEADER_SHOW_SET_RETRIEVED'
export const INVOICEHEADER_SHOW_TOGGLE_LOADING = 'INVOICEHEADER_SHOW_TOGGLE_LOADING'
