export const TEMPLATE_DELETE_RESET = 'TEMPLATE_DELETE_RESET'
export const TEMPLATE_DELETE_SET_ERROR = 'TEMPLATE_DELETE_SET_ERROR'
export const TEMPLATE_DELETE_SET_DELETED = 'TEMPLATE_DELETE_SET_DELETED'
export const TEMPLATE_DELETE_TOGGLE_LOADING = 'TEMPLATE_DELETE_TOGGLE_LOADING'
