export const TASKSTATUS_DELETE_RESET = 'TASKSTATUS_DELETE_RESET'
export const TASKSTATUS_DELETE_SET_ERROR = 'TASKSTATUS_DELETE_SET_ERROR'
export const TASKSTATUS_DELETE_SET_DELETED = 'TASKSTATUS_DELETE_SET_DELETED'
export const TASKSTATUS_DELETE_TOGGLE_LOADING = 'TASKSTATUS_DELETE_TOGGLE_LOADING'
