export const TEMPLATETYPE_SHOW_RESET = 'TEMPLATETYPE_SHOW_RESET'
export const TEMPLATETYPE_SHOW_SET_ERROR = 'TEMPLATETYPE_SHOW_SET_ERROR'
export const TEMPLATETYPE_SHOW_SET_RETRIEVED = 'TEMPLATETYPE_SHOW_SET_RETRIEVED'
export const TEMPLATETYPE_SHOW_TOGGLE_LOADING = 'TEMPLATETYPE_SHOW_TOGGLE_LOADING'
