export const DOCUMENT_SHOW_RESET = 'DOCUMENT_SHOW_RESET'
export const DOCUMENT_SHOW_SET_ERROR = 'DOCUMENT_SHOW_SET_ERROR'
export const DOCUMENT_SHOW_SET_RETRIEVED = 'DOCUMENT_SHOW_SET_RETRIEVED'
export const DOCUMENT_SHOW_TOGGLE_LOADING = 'DOCUMENT_SHOW_TOGGLE_LOADING'
