export const INVOICETYPE_SHOW_RESET = 'INVOICETYPE_SHOW_RESET'
export const INVOICETYPE_SHOW_SET_ERROR = 'INVOICETYPE_SHOW_SET_ERROR'
export const INVOICETYPE_SHOW_SET_RETRIEVED = 'INVOICETYPE_SHOW_SET_RETRIEVED'
export const INVOICETYPE_SHOW_TOGGLE_LOADING = 'INVOICETYPE_SHOW_TOGGLE_LOADING'
