export const PAYMENTTYPE_SHOW_RESET = 'PAYMENTTYPE_SHOW_RESET'
export const PAYMENTTYPE_SHOW_SET_ERROR = 'PAYMENTTYPE_SHOW_SET_ERROR'
export const PAYMENTTYPE_SHOW_SET_RETRIEVED = 'PAYMENTTYPE_SHOW_SET_RETRIEVED'
export const PAYMENTTYPE_SHOW_TOGGLE_LOADING = 'PAYMENTTYPE_SHOW_TOGGLE_LOADING'
