export const TASK_DELETE_RESET = 'TASK_DELETE_RESET'
export const TASK_DELETE_SET_ERROR = 'TASK_DELETE_SET_ERROR'
export const TASK_DELETE_SET_DELETED = 'TASK_DELETE_SET_DELETED'
export const TASK_DELETE_TOGGLE_LOADING = 'TASK_DELETE_TOGGLE_LOADING'
