export const SEARCH_UPDATE_QUERY = 'SEARCH_UPDATE_QUERY'
export const SEARCH_UPDATE_RESULTS = 'SEARCH_UPDATE_RESULTS'
export const SEARCH_ERROR_CHANGE = 'SEARCH_ERROR_CHANGE'
export const SEARCH_RESET = 'SEARCH_RESET'
