export const INVOICESTATUS_SHOW_RESET = 'INVOICESTATUS_SHOW_RESET'
export const INVOICESTATUS_SHOW_SET_ERROR = 'INVOICESTATUS_SHOW_SET_ERROR'
export const INVOICESTATUS_SHOW_SET_RETRIEVED = 'INVOICESTATUS_SHOW_SET_RETRIEVED'
export const INVOICESTATUS_SHOW_TOGGLE_LOADING = 'INVOICESTATUS_SHOW_TOGGLE_LOADING'
