export const ORDERSTATUS_SHOW_RESET = 'ORDERSTATUS_SHOW_RESET'
export const ORDERSTATUS_SHOW_SET_ERROR = 'ORDERSTATUS_SHOW_SET_ERROR'
export const ORDERSTATUS_SHOW_SET_RETRIEVED = 'ORDERSTATUS_SHOW_SET_RETRIEVED'
export const ORDERSTATUS_SHOW_TOGGLE_LOADING = 'ORDERSTATUS_SHOW_TOGGLE_LOADING'
