export const INVOICETYPE_DELETE_RESET = 'INVOICETYPE_DELETE_RESET'
export const INVOICETYPE_DELETE_SET_ERROR = 'INVOICETYPE_DELETE_SET_ERROR'
export const INVOICETYPE_DELETE_SET_DELETED = 'INVOICETYPE_DELETE_SET_DELETED'
export const INVOICETYPE_DELETE_TOGGLE_LOADING = 'INVOICETYPE_DELETE_TOGGLE_LOADING'
