export const BRAND_SHOW_RESET = 'BRAND_SHOW_RESET'
export const BRAND_SHOW_SET_ERROR = 'BRAND_SHOW_SET_ERROR'
export const BRAND_SHOW_SET_RETRIEVED = 'BRAND_SHOW_SET_RETRIEVED'
export const BRAND_SHOW_TOGGLE_LOADING = 'BRAND_SHOW_TOGGLE_LOADING'
