export const ORDERSTATUS_DELETE_RESET = 'ORDERSTATUS_DELETE_RESET'
export const ORDERSTATUS_DELETE_SET_ERROR = 'ORDERSTATUS_DELETE_SET_ERROR'
export const ORDERSTATUS_DELETE_SET_DELETED = 'ORDERSTATUS_DELETE_SET_DELETED'
export const ORDERSTATUS_DELETE_TOGGLE_LOADING = 'ORDERSTATUS_DELETE_TOGGLE_LOADING'
