export const PROJECTTYPE_DELETE_RESET = 'PROJECTTYPE_DELETE_RESET'
export const PROJECTTYPE_DELETE_SET_ERROR = 'PROJECTTYPE_DELETE_SET_ERROR'
export const PROJECTTYPE_DELETE_SET_DELETED = 'PROJECTTYPE_DELETE_SET_DELETED'
export const PROJECTTYPE_DELETE_TOGGLE_LOADING = 'PROJECTTYPE_DELETE_TOGGLE_LOADING'
