export const SHIPMENTMETHOD_SHOW_RESET = 'SHIPMENTMETHOD_SHOW_RESET'
export const SHIPMENTMETHOD_SHOW_SET_ERROR = 'SHIPMENTMETHOD_SHOW_SET_ERROR'
export const SHIPMENTMETHOD_SHOW_SET_RETRIEVED = 'SHIPMENTMETHOD_SHOW_SET_RETRIEVED'
export const SHIPMENTMETHOD_SHOW_TOGGLE_LOADING = 'SHIPMENTMETHOD_SHOW_TOGGLE_LOADING'
