export const TASK_SHOW_RESET = 'TASK_SHOW_RESET'
export const TASK_SHOW_SET_ERROR = 'TASK_SHOW_SET_ERROR'
export const TASK_SHOW_SET_RETRIEVED = 'TASK_SHOW_SET_RETRIEVED'
export const TASK_SHOW_TOGGLE_LOADING = 'TASK_SHOW_TOGGLE_LOADING'
