export const PROJECTTYPE_SHOW_RESET = 'PROJECTTYPE_SHOW_RESET'
export const PROJECTTYPE_SHOW_SET_ERROR = 'PROJECTTYPE_SHOW_SET_ERROR'
export const PROJECTTYPE_SHOW_SET_RETRIEVED = 'PROJECTTYPE_SHOW_SET_RETRIEVED'
export const PROJECTTYPE_SHOW_TOGGLE_LOADING = 'PROJECTTYPE_SHOW_TOGGLE_LOADING'
