export const PAYMENTTYPE_DELETE_RESET = 'PAYMENTTYPE_DELETE_RESET'
export const PAYMENTTYPE_DELETE_SET_ERROR = 'PAYMENTTYPE_DELETE_SET_ERROR'
export const PAYMENTTYPE_DELETE_SET_DELETED = 'PAYMENTTYPE_DELETE_SET_DELETED'
export const PAYMENTTYPE_DELETE_TOGGLE_LOADING = 'PAYMENTTYPE_DELETE_TOGGLE_LOADING'
