export const CHANNEL_DELETE_RESET = 'CHANNEL_DELETE_RESET'
export const CHANNEL_DELETE_SET_ERROR = 'CHANNEL_DELETE_SET_ERROR'
export const CHANNEL_DELETE_SET_DELETED = 'CHANNEL_DELETE_SET_DELETED'
export const CHANNEL_DELETE_TOGGLE_LOADING = 'CHANNEL_DELETE_TOGGLE_LOADING'
