export const PROJECTSTATUS_SHOW_RESET = 'PROJECTSTATUS_SHOW_RESET'
export const PROJECTSTATUS_SHOW_SET_ERROR = 'PROJECTSTATUS_SHOW_SET_ERROR'
export const PROJECTSTATUS_SHOW_SET_RETRIEVED = 'PROJECTSTATUS_SHOW_SET_RETRIEVED'
export const PROJECTSTATUS_SHOW_TOGGLE_LOADING = 'PROJECTSTATUS_SHOW_TOGGLE_LOADING'
