export const TEMPLATE_SHOW_RESET = 'TEMPLATE_SHOW_RESET'
export const TEMPLATE_SHOW_SET_ERROR = 'TEMPLATE_SHOW_SET_ERROR'
export const TEMPLATE_SHOW_SET_RETRIEVED = 'TEMPLATE_SHOW_SET_RETRIEVED'
export const TEMPLATE_SHOW_TOGGLE_LOADING = 'TEMPLATE_SHOW_TOGGLE_LOADING'
