export const VAT_SHOW_RESET = 'VAT_SHOW_RESET'
export const VAT_SHOW_SET_ERROR = 'VAT_SHOW_SET_ERROR'
export const VAT_SHOW_SET_RETRIEVED = 'VAT_SHOW_SET_RETRIEVED'
export const VAT_SHOW_TOGGLE_LOADING = 'VAT_SHOW_TOGGLE_LOADING'
